### PR TITLE
Extend Working Point script to Xbb

### LINKED ISSUE #53: Xbb working points
See https://github.com/umami-hep/atlas-ftag-tools/tree/main/ftag/wps

### PR DESCRIPTION
**Pull request by zcapjdb**
## Summary

This pull request introduces the following changes

* Extends the [wps.py](https://github.com/umami-hep/atlas-ftag-tools/blob/main/ftag/wps/working_points.py) script to include xbb tagging
*

Relates to the following issues

* closes #53 
*

## Conformity
- [x] [Changelog entry](https://github.com/umami-hep/atlas-ftag-tools/blob/main/changelog.md)
- [ ] [Documentation](https://umami-hep.github.io/atlas-ftag-tools/)

### CODE REVIEW

**Comment by samvanstroud** [comment]
Thanks @zcapjdb, it would be great if you could also update the mock file generation to include Xbb scores so that we can test this new functionality.

That would also be really useful for getting https://github.com/umami-hep/puma/pull/222 merged

**Comment by zcapjdb** [comment]
> Thanks @zcapjdb, it would be great if you could also update the mock file generation to include Xbb scores so that we can test this new functionality.
> 
> That would also be really useful for getting [umami-hep/puma#222](https://github.com/umami-hep/puma/pull/222) merged

I'll update the mock file yes, but one thing I realised is we do need to make a different update to the flavours.yaml file as the code looks for all flavours within the Xbb category, which complicates things with the two types of top label, or I change some of the logic to not cause this to break

**Comment by samvanstroud** [comment]
@zcapjdb thanks and yeah no worries, I think you can just create a new category for the top class you want to exclude

**Comment by samvanstroud** [comment]
Thanks for the update @zcapjdb! Looks good to me

**Review by samvanstroud — APPROVED** [review]

**Pull request merged**
